In [16]:
import pandas as pd

# Creating sample employee data
data = {
    "name": ["Aman", "Riya", "Neha", "Karan", "Pooja", "Rahul", "Sneha", "Arjun",
             "Kriti", "Vikas", "Anita", "Rohit"],
    "age": [22, 21, 23, 24, 22, 25, 21, 23, 22, 24, 26, 23],
    "salary": [25000, 27000, 26000, 30000, 28000, 32000, 24000,
               29000, 27500, 31000, 33000, 29500]
}

df = pd.DataFrame(data)

# Save DataFrame to CSV
df.to_csv("employee_data.csv", index=False)

# Load the CSV file
loaded_df = pd.read_csv("employee_data.csv")
loaded_df

     name  age  salary
0    Aman   22   25000
1    Riya   21   27000
2    Neha   23   26000
3   Karan   24   30000
4   Pooja   22   28000
5   Rahul   25   32000
6   Sneha   21   24000
7   Arjun   23   29000
8   Kriti   22   27500
9   Vikas   24   31000
10  Anita   26   33000
11  Rohit   23   29500

In [17]:
# First 5 rows
loaded_df.head()

# First 2 rows
loaded_df.head(2)

# Last 2 rows
loaded_df.tail(2)

# Type of object
type(loaded_df)

# First 10 rows
loaded_df.head(10)

    name  age  salary
0   Aman   22   25000
1   Riya   21   27000
2   Neha   23   26000
3  Karan   24   30000
4  Pooja   22   28000
5  Rahul   25   32000
6  Sneha   21   24000
7  Arjun   23   29000
8  Kriti   22   27500
9  Vikas   24   31000

In [18]:
# Save file with colon separator
loaded_df.to_csv("colon_file.txt", sep=":", index=False)

# Read colon separated file
colon_df = pd.read_table("colon_file.txt", sep=":")
colon_df

     name  age  salary
0    Aman   22   25000
1    Riya   21   27000
2    Neha   23   26000
3   Karan   24   30000
4   Pooja   22   28000
5   Rahul   25   32000
6   Sneha   21   24000
7   Arjun   23   29000
8   Kriti   22   27500
9   Vikas   24   31000
10  Anita   26   33000
11  Rohit   23   29500

In [19]:
# Skip first row
pd.read_csv("employee_data.csv", skiprows=1).head()

# Skip multiple rows
pd.read_csv("employee_data.csv", skiprows=[1, 2]).head()

    name  age  salary
0   Neha   23   26000
1  Karan   24   30000
2  Pooja   22   28000
3  Rahul   25   32000
4  Sneha   21   24000

In [20]:
# Saved normally
loaded_df.to_csv("saved_file.csv", index=False)

# Saved with custom separator
loaded_df.to_csv("saved_custom_sep.txt", sep="|", index=False)

In [21]:
import numpy as np

# Create NumPy array
arr = np.arange(1, 11)

# Convert to Series
series = pd.Series(arr)

# Save Series to CSV
series.to_csv("numpy_series.csv", index=False)

series

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64